services:
  bank_service_01:
    image: mybank:latest
    hostname: bank_service_01
    depends_on:
      - db
    ports:
      - "27001:27000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  bank_service_02:
    image: mybank:latest
    hostname: bank_service_02
    depends_on:
      - db
    ports:
      - "27002:27000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  nginx:
    image: nginx:latest
    depends_on:
      - bank_service_01
      - bank_service_02
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: nginx
