CREATE TABLE clientes (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(50) NOT NULL,
    limite int NOT NULL
);

INSERT INTO clientes (nome, limite) VALUES 
    ('a', 1000 * 100),
    ('b', 0),
    ('c', 10000 * 100);